# Generated by Django 3.0.6 on 2020-05-11 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='cart_item',
            name='total_price',
        ),
    ]
