# Generated by Django 3.0.6 on 2020-05-12 23:16

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_contact_info_order_payment_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_info',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='payment_info',
            name='expiration',
            field=models.DateField(),
        ),
    ]
