# Generated by Django 3.0.6 on 2020-05-12 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20200512_2316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_info',
            old_name='street',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='contact_info',
            name='house_nr',
        ),
    ]
