# Generated by Django 3.0.5 on 2020-05-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isadmin',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
