# Generated by Django 3.0.5 on 2020-05-04 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_isadmin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='isadmin',
            new_name='isAdmin',
        ),
    ]
