# Generated by Django 3.0.5 on 2020-05-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200506_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='searches',
            field=models.TextField(null='true'),
            preserve_default='true',
        ),
    ]
