# Generated by Django 3.0.5 on 2020-05-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('keywords', models.CharField(max_length=50, verbose_name='Keywords')),
                ('image', models.ImageField(upload_to=None, verbose_name='Image')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('desc', models.TextField(verbose_name='Description')),
                ('_type', models.CharField(max_length=50, verbose_name='Type')),
                ('price', models.IntegerField(verbose_name='Price')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
