# Generated by Django 3.0.5 on 2020-05-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
