# Generated by Django 3.0.5 on 2020-05-02 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_condition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='desc',
            new_name='description',
        ),
    ]
