# Generated by Django 3.0.5 on 2020-05-03 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200503_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_count',
            new_name='image',
        ),
    ]
